# author: Daniel Rode
# created: 16 Dec 2025


FROM docker.io/python:3.13

RUN python3 -m pip install \
  cycler \
  decorator \
  imageio \
  joblib \
  kiwisolver \
  laspy \
  matplotlib \
  networkx \
  numpy \
  opencv-python \
  Pillow \
  plyfile \
  pyparsing \
  python-dateutil \
  PyWavelets \
  scikit-image \
  scikit-learn \
  scipy \
  six \
;

RUN python3 -m pip install \
  absl-py \
  astunparse \
  cachetools \
  certifi \
  chardet \
  cycler \
  decorator \
  gast \
  google-auth \
  google-auth-oauthlib \
  google-pasta \
  grpcio \
  h5py \
  idna \
  imageio \
  importlib-metadata \
  joblib \
  Keras-Preprocessing \
  kiwisolver \
  laspy \
  Markdown \
  matplotlib \
  networkx \
  numpy \
  oauthlib \
  opencv-python \
  opt-einsum \
  Pillow \
  plyfile \
  protobuf \
  pyasn1 \
  pyasn1-modules \
  pyparsing \
  python-dateutil \
  PyWavelets \
  requests \
  requests-oauthlib \
  rsa \
  scikit-image \
  scikit-learn \
  scipy \
  six \
  tensorboard \
  tensorboard-plugin-wit \
  tensorflow \
  tensorflow-estimator \
  termcolor \
  urllib3 \
  Werkzeug \
  wrapt \
  zipp \
;
